name: Code Coverage
on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  codecov-ci-java:
    runs-on: ubuntu-latest
    steps:
      - name: Set up corretto 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install correct clang-format
        run: |
          sudo apt update
          sudo apt install clang-format-18
          sudo rm -rf $(which clang-format)
          ln $(which clang-format-18) /usr/local/bin/clang-format
      - name: Run Code Coverage Build
        env:
          TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
          ./tests/ci/run_accp_test_integration.sh
      - name: Upload Java coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

#  codecov-ci-cpp:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install lcov
#        run: |
#          sudo apt-get update -o Acquire::Languages=none -o Acquire::Translation=none
#          sudo apt-get -y install lcov
#      - uses: actions/checkout@v4
#      - name: Run Code Coverage Build
#        run: ./util/codecov-ci.sh ./build
#      - name: Upload code coverage report to Codecov
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: "./build/coverage-default.info,./build/coverage-no-asm.info"
#          verbose: true
#          fail_ci_if_error: true
